package com.example.lopez1407.testingdb.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.lopez1407.testingdb.dao.TestingDB;

import com.example.lopez1407.testingdb.dao.TestingDBDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig testingDBDaoConfig;

    private final TestingDBDao testingDBDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        testingDBDaoConfig = daoConfigMap.get(TestingDBDao.class).clone();
        testingDBDaoConfig.initIdentityScope(type);

        testingDBDao = new TestingDBDao(testingDBDaoConfig, this);

        registerDao(TestingDB.class, testingDBDao);
    }
    
    public void clear() {
        testingDBDaoConfig.getIdentityScope().clear();
    }

    public TestingDBDao getTestingDBDao() {
        return testingDBDao;
    }

}
