package com.example.lopez1407.testingdb.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table TESTING_DB.
 */
public class TestingDB {

    private Long id;
    private String Name;
    private String Phone;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public TestingDB() {
    }

    public TestingDB(Long id) {
        this.id = id;
    }

    public TestingDB(Long id, String Name, String Phone) {
        this.id = id;
        this.Name = Name;
        this.Phone = Phone;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public String getPhone() {
        return Phone;
    }

    public void setPhone(String Phone) {
        this.Phone = Phone;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
